"""Tests for the memory layer."""

import pytest
from codetruth.memory import MemoryLayer, MemoryType, MemoryEntry, MemorySpace


class TestMemoryLayer:
    """Test suite for MemoryLayer."""

    @pytest.fixture
    def memory(self, tmp_path):
        db_path = str(tmp_path / "test_memory.db")
        return MemoryLayer(db_path)

    def test_remember(self, memory):
        """Test storing a memory entry."""
        entry = memory.remember(
            memory_type=MemoryType.FACT,
            subject="test_function",
            content="This function was generated by Claude",
            context="src/main.py",
            importance=0.8,
            tags=["ai-generated", "python"],
        )
        assert entry is not None
        assert entry.memory_type == MemoryType.FACT
        assert entry.subject == "test_function"
        assert entry.importance == 0.8
        assert "ai-generated" in entry.tags

    def test_recall_by_type(self, memory):
        """Test recalling memories by type."""
        memory.remember(MemoryType.FACT, "fact1", "content1", importance=0.5)
        memory.remember(MemoryType.PREFERENCE, "pref1", "content2", importance=0.7)
        memory.remember(MemoryType.FACT, "fact2", "content3", importance=0.9)

        facts = memory.recall(memory_type=MemoryType.FACT)
        assert len(facts) == 2

        prefs = memory.recall(memory_type=MemoryType.PREFERENCE)
        assert len(prefs) == 1

    def test_recall_by_tag(self, memory):
        """Test recalling memories by tag."""
        memory.remember(MemoryType.FACT, "s1", "c1", tags=["python", "ai"])
        memory.remember(MemoryType.FACT, "s2", "c2", tags=["python", "web"])
        memory.remember(MemoryType.FACT, "s3", "c3", tags=["rust"])

        python_entries = memory.recall(tag="python")
        assert len(python_entries) == 2

        rust_entries = memory.recall(tag="rust")
        assert len(rust_entries) == 1

    def test_recall_by_subject(self, memory):
        """Test recalling memories by subject substring."""
        memory.remember(MemoryType.FACT, "calculate_sum", "c1")
        memory.remember(MemoryType.FACT, "calculate_avg", "c2")
        memory.remember(MemoryType.FACT, "format_string", "c3")

        results = memory.recall(subject_contains="calculate")
        assert len(results) == 2

    def test_recall_sorted_by_importance(self, memory):
        """Test that recall sorts by importance then recency."""
        memory.remember(MemoryType.FACT, "low", "c1", importance=0.1)
        memory.remember(MemoryType.FACT, "high", "c2", importance=0.9)
        memory.remember(MemoryType.FACT, "mid", "c3", importance=0.5)

        results = memory.recall()
        assert results[0].importance >= results[-1].importance

    def test_forget(self, memory):
        """Test forgetting a memory entry."""
        entry = memory.remember(MemoryType.FACT, "temp", "content")
        assert memory.forget(entry.memory_id) is True
        assert memory.forget("nonexistent") is False

        # Should not be recallable after forget
        results = memory.recall(memory_id=entry.memory_id)
        assert len(results) == 0

    def test_recall_recent(self, memory):
        """Test recalling recent memories."""
        memory.remember(MemoryType.FACT, "recent", "content")
        recent = memory.recall_recent(hours=24)
        assert len(recent) >= 1

    def test_create_space(self, memory):
        """Test creating a memory space."""
        space = memory.create_space("Python AI Code", "AI-generated Python code memories")
        assert space.name == "Python AI Code"
        assert space.space_id.startswith("space_")

    def test_add_to_space(self, memory):
        """Test adding memories to a space."""
        entry = memory.remember(MemoryType.FACT, "test", "content")
        space = memory.create_space("Test Space")

        assert memory.add_to_space(space.space_id, entry.memory_id) is True
        assert memory.add_to_space("nonexistent", entry.memory_id) is False

        retrieved_space = memory.get_space(space.space_id)
        assert entry.memory_id in retrieved_space.memory_ids

    def test_stats(self, memory):
        """Test memory statistics."""
        memory.remember(MemoryType.FACT, "s1", "c1")
        memory.remember(MemoryType.PREFERENCE, "s2", "c2")
        memory.remember(MemoryType.DECISION, "s3", "c3")

        stats = memory.stats()
        assert stats["total_entries"] == 3
        assert "by_type" in stats
        assert stats["by_type"]["fact"] == 1
        assert stats["by_type"]["preference"] == 1

    def test_memory_entry_to_dict(self, memory):
        """Test MemoryEntry serialization."""
        entry = memory.remember(MemoryType.FACT, "test", "content", tags=["tag1"])
        d = entry.to_dict()
        assert d["subject"] == "test"
        assert d["memory_type"] == "fact"
        assert "tag1" in d["tags"]